### ISSUE TITLE
🧬 Helix Bot - Setup Project

### ISSUE THREAD

**Issue by tripodsan** [tripodsan/hlxtest#37]
## Welcome to Project Helix.
This issue is used by the Helix Bot to track the progress of the project setup.

- [ ] Setup CDN Account
- [ ] Setup CDN Service
- [ ] Setup CI Account
- [ ] Setup Adobe IO Runtime Namespace
- [ ] Test Deployment
- [ ] Publish Site

The helix bot will update this issue accordingly and push updates to the internal
configuration to the `.github/helix-bot-config.yaml.gpg`.

**Comment by tripodsan** [comment]
---
state: foo
progress: failed
---

too bad

**Comment by tripodsan** [comment]
### Setup CDN

```yaml
step: setup-cdn
state: initial
progress: waiting
```

**Comment by tripodsan** [comment]
# Create CDN Service
```yaml
step: setup-cdn-service
state: initial
progress: waiting
```
